### ISSUE TITLE
[Linux] IDAPython: Error while calling Python callback <OnCreate>

### ISSUE THREAD

**Issue by hedgeberg** [patois/IDACyber#7]
On launching IDACyber via any method, I get:
```
Traceback (most recent call last):
  File "/home/hedge/ida-7.1/plugins/idacyber.py", line 870, in OnCreate
    self.filterlist = self._load_filters(self.pw)
  File "/home/hedge/ida-7.1/plugins/idacyber.py", line 794, in _load_filters
    filter = __import__(mod, globals(), locals(), [], 0)
ImportError: dynamic module does not define init function (initdbg)
Traceback (most recent call last):
  File "/home/hedge/ida-7.1/plugins/idacyber.py", line 243, in paintEvent
    if self.fm.support_selection:
AttributeError: 'NoneType' object has no attribute 'support_selection'
```

Running IDA 7.1 on Arch Linux with Qt5 and PyQt5 bindings installed. Any ideas on how best to troubleshoot?

Thanks!

**Comment by patois** [comment]
Do you get this error message with the "Dbg" filter only (you can try deleting cyber\dbg.py)? I have found the following on the net but I don't have a fix yet - will try to come up with a solution this weekend (I don't have a copy of IDA for Linux tho). https://stackoverflow.com/questions/24226001/importerror-dynamic-module-does-not-define-init-function-initfizzbuzz

**Comment by hedgeberg** [comment]
I'll give it a shot, see if it works. Also, I'm willing to debug and troubleshoot any solutions on my end. It's not the ideal solution but it'll work.

**Comment by hedgeberg** [comment]
Yup, just tested. It's just the dbg.py filter. Making a folder named nop and moving it to "nop/dbg.py.bak" causes idacyber to load just fine. Anything you want me to try changing, see if it makes a difference?

**Comment by patois** [comment]
Thanks for taking the time to test/verify. The 'Dbg' filter uses existing IDA debugger modules and may cause problems if it's used on architectures that do not come with any supported IDA debugger module at all or if there's no debugger currently set/configured. This is a known issue which is on the todo list.

Does the previous error occur as soon as you load IDACyber or only when you select the 'Dbg' filter (assuming the Dbg filter is not the first in the list of filters)?

**Comment by hedgeberg** [comment]
It happens as soon as I load an IDACyber window. I don't believe it's first in the list, but I don't know if there's a way to check to confirm if this is or is not the case.

**Comment by patois** [comment]
What is the underlying architecture of the file you are disassembling and running IDACyber with? Does the problem persist if a debugger module is available/set/configured before running IDACyber?

**Comment by patois** [comment]
I am currently looking into how to fix this properly. As an interim fix, you could try replacing the code at ~line 795 of idacyber.py with the following.

Original:
```
                filters.append((filter, filter.FILTER_INIT(pw)))
```

Patch:
```
                flt = filter.FILTER_INIT(pw)
                if flt is not None:
                    filters.append((filter, flt))

```

Please let me know if that fixes the issue with dbg.py!

**Comment by hedgeberg** [comment]
It does not seem to. I'm still getting the same crash. 
Also, this is an x86 binary, I was actually using a simple level from pwnable.kr to test my setup, you can throw the same binary at it if you want, its the one from the level "dragon". I'll try setting a debugger to see if it fixes it.

**Comment by hedgeberg** [comment]
Tried launching idacyber from the debug view, same error. Seems to be a fundamental error in how dbg.py is initializing, its curious that the "if not None" fix didn't fix it, too.

**Comment by patois** [comment]
I've just pushed an update to the master branch which doesn't specifically address this issue but I've glued some additional checks around it. Maybe you're lucky nontheless in case you wanna give it a try ;-)

edit: I've tried to most recent IDACyber on the "dragon" challenge from pwnable.kr - works fine here on my Windows VM, I'm unable to reproduce the issue :|

**Comment by patois** [comment]
Could you please try reproducing the bug with the most recent commit?

**Comment by hedgeberg** [comment]
Hey, sorry, I haven't been checking my emails for a while. I'll try to test in a bit and see if it behaves any differently!

**Comment by patois** [comment]
I was finally able to reproduce the issue. The problem was that if IDACyber wasn't installed into %idadir%/plugins (but to a user dir instead), it wouldn't find its color filters and hence was unable to load them. Let me know in case it doesn't work for you with the most recent commit. I haven't had the chance yet to test it on Linux myself tho.
