### ISSUE TITLE
IndexError: list index out of range self.pw.set_filter self.filterlist

### ISSUE THREAD

**Issue by trietptm** [patois/IDACyber#9]
Hi, I started IDACyber and receive this error message:
> IDAPython: Error while calling Python callback <OnCreate>:
> Traceback (most recent call last):
>   File "D:/IDA 7.x/plugins/idacyber.py", line 1083, in OnCreate
>     self.pw.set_filter(self.filterlist[0][1], 0)
> IndexError: list index out of range

**Comment by patois** [comment]
Hi,
thanks for bringing up this issue. It was caused due to faulty indentation. Please try commit https://github.com/patois/IDACyber/commit/a571df2df43ffc22193f617a07507e4bd0e45abd and let me know whether it fixes the issue so it can be closed. Thanks :)

**Comment by trietptm** [comment]
The issue is fixed now :) .
